version: 3

silent: true

tasks:
  default: task --list

  terminal:
    desc: open a terminal in the dev container
    aliases:
      - shell
      - sh
      - zsh
    cmds:
      - docker exec -it -w /workspaces/aws-auto-alarm -u vscode aws_auto_alarm_devcontainer /usr/bin/zsh

  step-functions-local:
    desc: run step functions locally
    aliases:
      - sf-local
      - sfl
    cmds:
      - |
        docker run \
          --name sf_local \
          --rm \
          --detach \
          -p 8083:8083 \
          --mount type=bind,readonly,source=$(pwd)/statefiles/mock/mockconfig.json,destination=/home/StepFunctionsLocal/MockConfigFile.json \
          -e SFN_MOCK_CONFG="/home/StepFunctionsLocal/MockConfigFile.json" \
          amazon/aws-stepfunctions-local:1.14.0
