version: 3

silent: true

tasks:
  default: task --list

  clean:
    desc: remove files
    aliases:
      - c
    cmds:
      - rm -rf ./out

  step-functions-local:
    desc: run step functions locally
    aliases:
      - sf-local
      - sfl
    cmds:
      - |
        docker run \
          --name sf_local \
          --rm \
          --detach \
          -p 8083:8083 \
          --mount type=bind,readonly,source=$(pwd)/statefiles/mock/mockconfig.json,destination=/home/StepFunctionsLocal/MockConfigFile.json \
          -e SFN_MOCK_CONFG="/home/StepFunctionsLocal/MockConfigFile.json" \
          amazon/aws-stepfunctions-local:1.14.0

  cmd:test:
    desc: run a sample file through the command
    aliases:
      - ct
    cmds:
      - go run ./cmd/aws_auto_alarm --file ./sample_cli_input.json

  test:accept:
    desc: run acceptance tests
    aliases:
      - ta
    vars:
      GO_VERSION: 1.22
      GOTESTSUM_VERSION: v1.12.0
    cmds:
      - |
        docker run \
          --rm \
          --mount type=bind,source=$(pwd),destination=/app \
          -w /app \
          golang:{{ .GO_VERSION }} \
          go run gotest.tools/gotestsum@{{ .GOTESTSUM_VERSION }} --format pkgname-and-test-fails --junitfile /app/out/test-results.xml -- -v ./test/acceptance

  lint:
    desc: run linter
    aliases:
      - l
    vars:
      GOLANGCI_LINT_VERSION: v1.59.1
    cmds:
      - |
        docker run \
          --rm \
          --mount type=bind,source=$(pwd),destination=/app \
          -w /app \
          golangci/golangci-lint:{{ .GOLANGCI_LINT_VERSION }} \
          golangci-lint run -v
