version: 3

silent: true

tasks:
  default: task --list

  step-functions-local:
    desc: run step functions locally
    aliases:
      - sf-local
      - sfl
    cmds:
      - |
        docker run \
          --name sf_local \
          --rm \
          --detach \
          -p 8083:8083 \
          --mount type=bind,readonly,source=$(pwd)/statefiles/mock/mockconfig.json,destination=/home/StepFunctionsLocal/MockConfigFile.json \
          -e SFN_MOCK_CONFG="/home/StepFunctionsLocal/MockConfigFile.json" \
          amazon/aws-stepfunctions-local:1.14.0

  cmd:test:
    desc: run a sample file through the command
    aliases:
      - ct
    cmds:
      - go run ./cmd/aws_auto_alarm --file ./sample_cli_input.json
